pipeline {
    agent any 
    parameters {
        
        choice (
            name: 'Versions',
            choices: 'v1\nv2'
            description: 'Choose version type'
            )
    }
    
    stages {
        stage('Build') { 
            steps {
                // Can access parameters by using params.
                if (params.Versions == 'v1')
                {
                  stage (checkout) {
                      steps{
                       git branch: 'main',
                        // credentialsId: 'Credential ID',
                        url: 'https://github.com/chndel-abhishek/nodejs.git'
                  
                        }
                      }
                stage (build) {
                    sh "cd Ansible && ansible-playbook -i ./inventory.txt v1-playbook.yaml"
                }
                }
                else
                {
                    // release build
                }
            }
        }
        stage('Test') { 
            when {
                // This stage is processed only when UseTest is true.
                environment name: 'UseTest', value: 'true'
            }
            steps {
                 
            }
        }
        stage('Deploy') { 
            steps {

            }
        }
    }
}