apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    name: frontend
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
             image: abhishek7868/frontend:v3
          imagePullPolicy: Always
          env:
            - name: COUNTER_ENDPOINT
              value: "http://backend.default.svc.cluster.local:5000"
          ports:
            - name: frontend-port
              containerPort: 8000
              protocol: TCP

