---
- name: Clone and Deploy Node.js App
  hosts: all
  become: yes
 
  tasks:
    - name: make a directory
      ansible.builtin.file:
        path: /home/abhishekchandel1411/Ansible/
        state: directory
        mode: '0755'
    - name: make a directory
      ansible.builtin.file:
        path: /home/abhishekchandel1411/Ansible/V2
        state: directory
        mode: '0755'    
    - name: Download Artifacts
      command: curl -u admin:admin -o sample-app-2.0.0.tgz "http://34.83.246.129:8081/repository/npm-hosted/sample-app/-/sample-app-2.0.0.tgz && echo 'pwd'>workin.txt"
      become: yes

    - name: Extract the file
      ansible.builtin.unarchive:
        src: /var/lib/jenkins/workspace/Build_task_abhishek@2/sample-app-2.0.0.tgz
        dest: /home/abhishekchandel1411/Ansible/V2
     
    - name: "Install nodejs"
      apt:
         update_cache: yes
         name: 
         - nodejs
         - npm
         - nginx
         state: present
   
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/Build_task_abhishek/Ansible/mynodejs.service
        dest: /etc/systemd/system/
        mode: '0644'
        follow: yes 
    
    - name: Enable service nodejs service
      command: "systemctl enable mynodejs"
      become: yes

    - name: Make sure a service unit is running
      command: "systemctl start mynodejs"
